[plugins]
gradle_versions = { id = "com.github.ben-manes.versions", version = "0.42.0" }
forge_gradle_three = { id = "net.minecraftforge.gradle", version = "5.1.56" }
parchment_librarian = { id = "org.parchmentmc.librarian.forgegradle", version = "1.2.0" }
